# Generated by Django 3.1.4 on 2020-12-14 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=200, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                ("producer", models.CharField(max_length=200, verbose_name="Producer")),
                (
                    "wrn_tsh",
                    models.PositiveIntegerField(verbose_name="Warning Threshold"),
                ),
                ("barcode", models.PositiveIntegerField(verbose_name="Barcode")),
                (
                    "lastchange",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Last change on"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "lastchange_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_edited",
                        to="accounts.userprofile",
                        verbose_name="Last change by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.PositiveIntegerField(verbose_name="Package size")),
                ("barcode", models.PositiveIntegerField(verbose_name="Barcode")),
                (
                    "lastchange",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Last change on"
                    ),
                ),
                (
                    "lastchange_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages_edited",
                        to="accounts.userprofile",
                        verbose_name="Last change by",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package",
                "verbose_name_plural": "Packages",
                "ordering": ["product"],
            },
        ),
    ]
