version: '3.5'

services:
  app:
    read_only: true
    build: .
    image: "${DT_IMAGE:-discipline-terra}"
    ports:
      - 8080:8080
    volumes:
      - type: tmpfs
        target: /tmp
    depends_on:
      - postgres

  postgres:
    read_only: true
    image: postgres:9.6.11-alpine
    volumes:
      - type: bind
        source: ./postgres-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./postgres-tmp
        target: /var/run
      - type: tmpfs
        target: /tmp
    ports:
      - 5432:5432
