# Generated by Django 3.1.4 on 2020-12-14 16:13

import django.db.models.deletion
from django.db import migrations, models

import invoices.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("accounts", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Invoiced on"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.CreateModel(
            name="Voice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                (
                    "unit_price_novat",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit price"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit price"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "amount_novat",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                ("pieces", models.PositiveIntegerField(verbose_name="Pieces")),
                (
                    "vat",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="VAT"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.invoice",
                        verbose_name="Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice",
                "verbose_name_plural": "Voices",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Recorded on"),
                ),
                (
                    "lastchange",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Last change on"
                    ),
                ),
                (
                    "invoiced",
                    models.BooleanField(default=False, verbose_name="Invoiced"),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.catalog",
                        verbose_name="Catalog",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "lastchange_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_edited",
                        to="accounts.userprofile",
                        verbose_name="Last change by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["record_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceHeading",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "long_name",
                    models.CharField(max_length=200, verbose_name="Full name"),
                ),
                ("address", invoices.modelfields.AddressField(verbose_name="Address")),
                (
                    "tax_code",
                    models.CharField(
                        max_length=200, verbose_name="Tax code or Vat code"
                    ),
                ),
                ("phone", models.CharField(max_length=200, verbose_name="Phone")),
                ("email", models.EmailField(max_length=200, verbose_name="Email")),
                (
                    "logo_filename",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="logos",
                        verbose_name="Logo file",
                    ),
                ),
                (
                    "usual_title_respect",
                    models.CharField(
                        max_length=200, verbose_name="Usual title respect"
                    ),
                ),
                (
                    "lastchange",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Last change on"
                    ),
                ),
                (
                    "lastchange_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_headings_edited",
                        to="accounts.userprofile",
                        verbose_name="Last change by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoce Heading",
                "verbose_name_plural": "Invoice Headings",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="heading_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices_entitled",
                to="invoices.invoiceheading",
                verbose_name="Invoice as",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="issuer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices_issued",
                to="accounts.userprofile",
                verbose_name="Issued by",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices_paid",
                to="invoices.payment",
                verbose_name="Payment type",
            ),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pieces", models.PositiveIntegerField(verbose_name="Pieces")),
                (
                    "record_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Recorded on"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.price",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Item",
                "ordering": ["record_date"],
                "unique_together": {("order", "price")},
            },
        ),
    ]
