# Generated by Django 3.1.4 on 2020-12-14 16:13

import django.db.models.deletion
from django.db import migrations, models

import invoices.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("surname", models.CharField(max_length=200, verbose_name="Surname")),
                ("address", invoices.modelfields.AddressField(verbose_name="Address")),
                (
                    "tax_code",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Tax code"
                    ),
                ),
                (
                    "vat_code",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Vat code"
                    ),
                ),
                ("phone", models.CharField(max_length=200, verbose_name="Phone")),
                ("email", models.EmailField(max_length=200, verbose_name="Email")),
                (
                    "record_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Recorded on"),
                ),
                (
                    "lastchange",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Last change on"
                    ),
                ),
                (
                    "lastchange_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_edited",
                        to="accounts.userprofile",
                        verbose_name="Last change by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["surname", "name"],
                "get_latest_by": "surname",
                "unique_together": {("tax_code", "vat_code")},
            },
        ),
    ]
