# Generated by Django 3.1.4 on 2020-12-14 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stock", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, unique=True, verbose_name="Title"),
                ),
            ],
            options={
                "verbose_name": "Catalog",
                "verbose_name_plural": "Catalogs",
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_in",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price IN"
                    ),
                ),
                (
                    "vat_in",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="VAT IN"
                    ),
                ),
                (
                    "gain_percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Gain"
                    ),
                ),
                (
                    "vat_out",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="VAT OUT"
                    ),
                ),
                (
                    "lastchange",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Last change on"
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.catalog",
                        verbose_name="Catalog",
                    ),
                ),
                (
                    "lastchange_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_edited",
                        to="accounts.userprofile",
                        verbose_name="Last change by",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price",
                "verbose_name_plural": "Prices",
                "ordering": ["product"],
                "unique_together": {("catalog", "product")},
            },
        ),
    ]
