#!/bin/bash
# The following settings are expected to be defined in container enviroment running postgres
# DJANGO_POSTGRES_DBNAME=...
# DJANGO_POSTGRES_DBUSER=...
# DJANGO_POSTGRES_DBPASSWD=...
# DJANGO_POSTGRES_DBHOST=...


set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${DJANGO_POSTGRES_DBUSER} WITH PASSWORD '${DJANGO_POSTGRES_DBPASSWD}';
    CREATE DATABASE ${DJANGO_POSTGRES_DBNAME} OWNER ${DJANGO_POSTGRES_DBUSER};
    GRANT ALL PRIVILEGES ON DATABASE ${DJANGO_POSTGRES_DBNAME} TO ${DJANGO_POSTGRES_DBUSER};
EOSQL
